# This is the name of the workflow, visible on GitHub UI
name: Google Java Format

# Trigger the workflow on push or pull request
on: [push, pull_request]

#A workflow run is made up of one or more jobs. Jobs run in parallel by default.
jobs:
  formatting:
    #The type of machine to run the job on. [windows, macos, ubuntu, self-hosted]
    runs-on: ubuntu-latest
    #sequence of tasks called
    steps:
      # The branch or tag ref that triggered the workflow will be checked out.
      # https://github.com/actions/checkout
      - uses: actions/checkout@v3
      # will format all Java files in the repository and commit the changes.
      - uses: axel-op/googlejavaformat-action@v3.6.0
        with:
          args: "--skip-sorting-imports --replace"
